### ISSUE TITLE
website previews

### ISSUE THREAD

**Issue by blacklist-arcc** [evait-security/envizon#1]
add an option to create screenshots from web applications / websites and embedd them into the single host view (quick preview).

suggestions:
https://github.com/maxwell/screencap
https://github.com/vitalie/webshot

**Comment by evs-pn** [comment]
https://github.com/FortyNorthSecurity/EyeWitness

Checkout this Tool. Maybe a good all in one solution.

**Comment by evs-pn** [comment]
https://tools.kali.org/information-gathering/eyewitness

**Comment by evs-pn** [comment]
We will work in this now. The feature will implemented like Shodan Images work.

**Comment by evs-ch** [comment]
selenium-webdriver was added in f517b27.
Use it with:
```
wd = SELENIUM
wd.navigate.to 'https://www.google.com'
wd.manage.window.resize_to(1920, 1080)
img =  wd.screenshot_as(:png)
```

("inspired" by https://gist.github.com/elcamino/5f562564ecd2fb86f559. If you want to write it to a file as described there, you need to use `wb` instead of `w+`. )

We should probably set the options globally in the selenium-initializer and create a new selenium instance for each use instead of using a global one. I'll get to that maybe soonish™.

**Comment by evs-ch** [comment]
Switched to a non-global webdriver in 4f47aac.

So usage would now be:

 ```ruby
wd = Selenium::WebDriver.for :remote, url: 'http://localhost:4444/wd/hub', desired_capabilities: SELENIUM_CAPS
wd.manage.timeouts.page_load = 60
wd.navigate.to 'https://www.google.com'
wd.manage.window.resize_to(1920, 1080)
img =  wd.screenshot_as(:png)
```

ActiveStorage wants to get an io-Object, so the `img` could probably be used more or less like this:
```ruby
yourobject.somefile.attach(io: StringIO.new(img), filename: 'somefilename.png', content_type: 'image/png'
```

**Comment by blacklist-arcc** [comment]
implemented in dev-branches. will released in a few days on master and dockerhub
