### ISSUE TITLE
Exposed ports

### ISSUE THREAD

**Issue by Alex-0293** [evait-security/envizon#57]
### Prerequisites (This part should not be included in any issue)
- I have read the readme file & wiki
- I am running the latest version (`git pull && docker-compose build`)
- I have searched through the existing issues to ensure my issue is not already covered
- I do not report any visual issues relating to responsive design if my screen is not able to display more than 720p (1280×720)
- I do not report any visual issues relating to usage in old / unsupported browsers
- I use `docker-compose build`, the prebuilt images from the official repositories, or installed envizon without any problems on my own

Issues violating these prerequisites will be closed without further explanation. Furthermore, you will be haunted by your own shameful behavior for the rest of your life.

### Description
I want to change app port
3000 is under grafana.
What should i do?
Please describe the problem or idea with as much detail as possible.

### Steps to Reproduce

Provide any information to reproduce the issue.

**Comment by evs-ch** [comment]
Assuming you're using docker-compose, you can just specify a different port in your `docker-compose.yml`, like:

```yaml
    ports:
      - 3001:3000
```

When running it without using docker, you could probably specify a different port when running `bundle exec rails s` or, should that fail due to the TLS config for production use, just edit your `config/puma.rb` accordingly.
