### ISSUE TITLE
Unknown MySQL server host 'mysql' (-2)

### ISSUE THREAD

**Issue by noraj** [evait-security/envizon#70]
### Description

`Unknown MySQL server host 'mysql' (-2)` error when trying to add an issue as issue template to remote database.

![image](https://user-images.githubusercontent.com/16578570/93402092-17fc3e80-f884-11ea-9e59-581ec4428a0c.png)

Instance deployed via [Running from local git checkout](https://github.com/evait-security/envizon#running-from-local-git-checkout).

**Comment by blacklist-arcc** [comment]
This feature isn't documented very well because it's currently in beta status. Nevertheless we heavily use this for our pentests so this should be fine. Please check the settings page and select issue templates. As introduced in the readme file we now store the issue templates in a remote and independent mysql database so you can save the templates in a central way independent from the envizon instance. For that purpose you need a mysql server/instance. Follow the instructions on the settings section. After that you can download all templates from the remote database to envizon (like a cache) and edit/add them live in envizon. The save to cloud button allows you to sync your changes directly to the remote database so that you can use them in the next envizon instance. If you have any further questions please feel free to contact us.
